### ISSUE TITLE
Create good error handling

### ISSUE THREAD

**Issue by Rycieos** [Calvin-TMO/TMO#16]
Each page that allows you to input values should have a full input check to make sure the values are valid and redirects back to page if errors.
List pages should have ability to display success messages when a new entry is added and redirected back
        Partnered with @WiensCarson 
        Due by: Tues, Apr 19th

**Comment by WiensCarson** [comment]
**Input Checks:**
user_add
user_edit
course_add
course_edit
assignment_add
assignment_edit
report_add
report_edit

**Success Message:**
user_edit (after adding new roles/courses)
user (after creating new user or editing user's name)
course_edit (after adding professor and/or tutor)
course (after creating new course or editing course's info)
assignment (after editing an assignment)
report (after editing or creating a report or adding/removing a comment)

**Misc.**
All back buttons redirect to previously visited page
Add ability to edit user's name
