### ISSUE TITLE
Fix seeds

### ISSUE THREAD

**Issue by Rycieos** [Calvin-TMO/TMO#17]
Restructure to use Laravel programmable seeding abilities (you shouldn't need additional scripts as the seeds are a script in them selves).

Add dates and times to report seeds.
        Due by: Tues, Apr 12th

**Comment by Rycieos** [comment]
The default seed data also still needs to be removed.

Users:
    tutor1,2
    student1,2
    professor1,2

Note that this was done by me in commit 5d01ee2d8a57c3bed897168e1d9d0bf161360d29, but that change is not part of any merged code right now.

**Comment by Rycieos** [comment]
Note that often the courses that tutor is assigned to tutor do not match up with what they actually tutor. This would be nice to have fixed in the seeds, but I'm not sure if it is really needed.

**Comment by WiensCarson** [comment]
I found this a while ago and decided it was a bit too complex for dummy
data when we aren't sorting by tutor's classes anyway

**Comment by WiensCarson** [comment]
Right now I'm not sure what more I can do in terms of optimizing seeding.
Reports and UserRoles were the main hogs, and those have been efficiently
slain.
Any suggestions? Otherwise I will submit a pull request.

**Comment by Rycieos** [comment]
As long as the issues above are fixed, namely: 
- Add dates and times to report seeds
- Remove the default seed data  

and the seeds actually get into the DB fine (ie no errors) then I would say that this is done. You can submit a pull request.

**Comment by WiensCarson** [comment]
Fantastic! These things were accomplished yesterday. I will submit a pull
request.
