### ISSUE TITLE
Fix emails

### ISSUE THREAD

**Issue by Rycieos** [Calvin-TMO/TMO#18]
Fix password reset emails to not be caught by spam filters.

Make emails be sent when a new report/comment is made.
        Due by: Tues, Apr 19th

**Comment by WiensCarson** [comment]
Fixed this bug already! Try it for yourself!

**Comment by Rycieos** [comment]
Your changes are not in master, so it is not fixed. If your code is done and it fixes this issue, create a pull request.

**Comment by Rycieos** [comment]
Fixed in #23
